[theme]
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"

[theme.sidebar]
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"

[client]
showSidebarNavigation = false

